# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "pry", "~> 0.13.1"

gem "sinatra", "~> 2.1"

gem "sidekiq", "~> 6.1"

gem "redis", "~> 4.2"
